<?php
/**
 * Implements hook_form_BASE_FORM_ID_alter(): node_form.
 */
 
 $checkbox_field = "field_checkbox[und]";
 
function our_module_form_node_form_alter(&$form, &$form_state, $form_id) {
	switch ($form_id) {
		case 'bid_node_form':
		case 'application_form_for_listener_node_form':

			array_unshift($form['#validate'], 'my_validate');
			
			$form['additional_settings']['#access'] = 0;
			$form['#after_build'][] = 'set_title';
			
			set_required(0);			
			
			$form['field_tags']['#states'] = array(
			'visible' => array(
			  'input[name="field_will_be_published[und]"]' => array('checked' => TRUE)
				),
			'required'=> array(
			  'input[name="field_will_be_published[und]"]' => array('checked' => TRUE)
				),
			);
			$form['field_abstract']['#states'] = 
			$form['title']['#states'] = 
			$form['field_abstract']['#states'] = 
			$form['field_need_accommodation']['#states'] = $form['field_tags']['#states'];
			$form['field_addition_information']['#states'] = array(
			'visible' => array(
			  'input[name="field_will_be_published[und]"]' => array('checked' => TRUE)
				),
			);
		break;
	}
}

function my_validate(&$form, &$form_state){
	if(!$form['field_will_be_published']['und']['#value']){
		$form['title']['#required'] = 0;
		$form['title']['#value']='Default value';	
		$form['#node']->title='Default value';	
		$form['#entity']->title='Default value';
		print '<pre>';
		print_r($form);
		die();
	}
	else{
		if(count($form['field_tags']['und']['#value'])==0){
			form_set_error('Section', t('Field "Section" is required.'));
		}
		if(!$form['field_abstract']['und']['#file']){
			form_set_error('Abstract', t('Field "Abstract" is required.'));
		}
		
	}
}

function set_required($required){
	$form['field_tags']['#required'] = $required;
	$form['title']['#required'] = $required;
	$form['field_abstract']['#required'] = $required;
	$form['field_need_accommodation']['#required'] = $required;
	$form['field_addition_information']['#required'] = $required;
}

function set_title($form, &$form_state){
	drupal_set_title(t('Registration for the conference'));
	/*
	print '<pre>';
	print_r($form);
	die();*/
	return $form;
}